apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
  labels:
    app: apiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiservice
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      containers:
        - name: apiservice
          image: badhmanabanm/datacache:latest
          resources:
            limits:
              cpu: 10m
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: config-file
              mountPath: /config.json
              subPath: config.json
      volumes:
        - name: config-file
          configMap:
            name: apiservice-config
---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
  labels:
    app: apiservice
spec:
  selector:
    app: apiservice
  ports:
    - name: http
      port: 80
      targetPort: 9000
  type: LoadBalancer
---
apiVersion: v1
data:
  config.json: |-
    {
        "app_name": "data_cache_v1",
        "port": "9000",
        "read_timeout": 30,
        "write_timeout": 180,
        "max_idle_time_out": 240,
        "redis_vars": {
          "conn_string": "127.0.0.1:6379",
          "max_retries": 3,
          "min_retry_backoff": 120,
          "dial_timeout": 6,
          "read_timeout": 12,
          "write_timeout": 15
        },
        "database": {
          "type": "MongoDB",
          "name": "datacache",
          "uri": "mongodb://mongodb:27017",
          "source": "admin",
          "user_name": "",
          "password": ""
          "timeout": 30,
          "pool_timeout": 12,
          "pool_conn_maxidle_time": 60000,
          "pool_limit": 100
        },
        "backupServiceURL": "127.0.0.1:9001"
      }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: apiservice-config