apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerjobs
  labels:
    app: workerjobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workerjobs
  template:
    metadata:
      labels:
        app: workerjobs
    spec:
      containers:
        - name: workerjobs
          image: badhmanabanm/worker_service:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 10m
          volumeMounts:
            - name: config-file
              mountPath: /config.json
              subPath: config.json
      volumes:
        - name: config-file
          configMap:
            name: worker-config
---
apiVersion: v1
kind: Service
metadata:
  name: workerjobs
  labels:
    app: workerjobs
spec:
  externalIPs:  
    - 192.168.39.140
  selector:
    app: workerjobs
  ports:
    - name: http
      port: 81
      targetPort: 9096
  type: LoadBalancer
---
apiVersion: v1
data:
  config.json: |-
    {
      "app_name": "data_cache_v1",
      "redis_vars": {
        "conn_string": "redis:6379",
        "max_retries": 3,
        "min_retry_backoff": 120,
        "dial_timeout": 6,
        "read_timeout": 12,
        "write_timeout": 15
      },
      "database": {
        "type": "MongoDB",
        "name": "datacache",
        "uri": "mongodb://mongodb:27017",
        "source": "admin",
        "timeout": 30,
        "pool_timeout": 12,
        "user_name": "root",
        "password": "gz7MXGjAFg",
        "pool_conn_maxidle_time": 60000,
        "pool_limit": 100
      },
      "scheduler_db_backup": 1,
      "kafka": {
        "broker_address" : ["kafka:9093"],
        "topic": "restore_user"
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: worker-config